drm: drop unused Linux-only header after a90e359fc477
src/drm.cpp:4:10: fatal error: 'linux/limits.h' file not found
 #include <linux/limits.h>
          ^~~~~~~~~~~~~~~~