rendervulkan: add missing header for libc++ 16 after 191a85da047f
In file included from src/drm.cpp:21:
In file included from src/drm.hpp:89:
src/rendervulkan.hpp:774:7: error: no type named 'mutex' in namespace 'std'
        std::mutex m_pipelineMutex;
        ~~~~~^